export const STORAGE = Symbol('STORAGE');

export interface StorageService {
  // Saves the file and returns its public URL
  save(key: string, body: Buffer, contentType: string): Promise<string>;
}

// "https://cdn.example.com/" + "images/a.webp" → "https://cdn.example.com/images/a.webp"
export function publicUrlFor(baseUrl: string, key: string): string {
  return `${baseUrl.replace(/\/+$/, '')}/${key.replace(/^\/+/, '')}`;
}

// Keys are generated by us; this guards against any path tricks anyway.
export function assertSafeKey(key: string): void {
  if (!/^[a-z0-9][a-z0-9/_-]*\.[a-z0-9]+$/i.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}
